name: Deploy ParakshTech

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script_stop: true
          script: |
            set -eux

            cd /var/www/parakshtech.com

            echo "=== Pull latest code ==="
            git pull origin main

            echo "=== Node ==="
            node -v

            echo "=== NPM ==="
            npm -v

            echo "=== Install ==="
            npm ci

            echo "=== Build ==="
            npm run build

            echo "=== Nginx test ==="
            sudo nginx -t

            echo "=== Reload Nginx ==="
            sudo systemctl reload nginx

            echo "=== DEPLOYMENT SUCCESS ==="
