name: Deploy ParakshTech

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 173.212.235.87
          username: root
          password: 11IT13manoj
          port: 22
          script_stop: true
          script: |
            echo "SSH connection successful"
            echo "Server hostname:"
            hostname

            echo "Testing directory..."
            cd /var/www/parakshtech.com
            pwd
            ls -la
